# Generated by Django 5.2 on 2025-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_text', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tracks',
        ),
    ]
