# Generated by Django 5.2 on 2025-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_track_delete_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='html_text',
        ),
        migrations.AddField(
            model_name='track',
            name='album_or_playlist_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='is_album',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
