# Generated by Django 5.2 on 2025-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_remove_track_html_text_track_album_or_playlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('artists', models.CharField()),
                ('track_id', models.CharField()),
                ('album_or_playlist_id', models.CharField()),
                ('is_album', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
