# Generated by Django 5.2 on 2025-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_track_delete_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('artists', models.CharField()),
                ('head_id', models.CharField()),
                ('is_album', models.CharField()),
            ],
        ),
    ]
